-- ============================================
-- SUPABASE SETUP - Our Galaxy Project
-- ============================================
-- Este arquivo contém todas as tabelas, políticas RLS e configurações
-- necessárias para o funcionamento completo do aplicativo.

-- ============================================
-- 1. TABELA: ABSENCES (Saudades)
-- ============================================
create table public.absences (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  text text not null,
  author_id text not null,
  type text default 'miss'
);

-- Habilitar RLS
alter table public.absences enable row level security;

-- Política de acesso (Simplificada para uso com strings 'nana'/'fefe')
create policy "Enable access to all users" on public.absences for all using (true);

-- ============================================
-- 2. TABELA: LETTERS (Cartas)
-- ============================================
create table public.letters (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  preview text,
  author_id text not null,
  recipient_id text not null,
  likes int default 1
);

-- Habilitar RLS
alter table public.letters enable row level security;

-- Política de acesso
create policy "Enable access to all users" on public.letters for all using (true);

-- ============================================
-- 3. TABELA: MOMENTS (Momentos)
-- ============================================
create table public.moments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date_memory date not null,
  time_memory time,
  description text not null,
  media_url text not null,
  media_type text not null,
  author_id text not null
);

-- Habilitar RLS
alter table public.moments enable row level security;

-- Política de acesso
create policy "Enable access to all users" on public.moments for all using (true);

-- ============================================
-- 4. STORAGE BUCKET: moments-media
-- ============================================
-- Execute os passos abaixo manualmente no painel Supabase:
--
-- 1. Vá para a seção "Storage"
-- 2. Clique em "New Bucket"
-- 3. Nome: "moments-media"
-- 4. Ative a opção "Public bucket" (ON)
-- 5. Clique em "Save"
--
-- Depois, configure as políticas:
--
-- POLÍTICA DE LEITURA (SELECT):
-- - Policy Name: "Public Access"
-- - Allowed Operation: SELECT
-- - Target roles: anon
-- - USING expression: true
--
-- POLÍTICA DE UPLOAD (INSERT):
-- - Policy Name: "Public Upload"
-- - Allowed Operation: INSERT
-- - Target roles: anon
-- - WITH CHECK expression: true

-- ============================================
-- 5. ÍNDICES PARA PERFORMANCE
-- ============================================
create index idx_absences_author_id on public.absences(author_id);
create index idx_absences_created_at on public.absences(created_at desc);

create index idx_letters_author_id on public.letters(author_id);
create index idx_letters_recipient_id on public.letters(recipient_id);
create index idx_letters_created_at on public.letters(created_at desc);

create index idx_moments_author_id on public.moments(author_id);
create index idx_moments_created_at on public.moments(created_at desc);
create index idx_moments_date_memory on public.moments(date_memory desc);

-- ============================================
-- 6. DADOS DE EXEMPLO (OPCIONAL)
-- ============================================
-- Descomente as linhas abaixo para popular com dados de teste

-- INSERT INTO public.absences (text, author_id, type) VALUES
-- ('Sinto sua falta quando você não está aqui', 'fefe', 'miss'),
-- ('Você faz falta no meu dia', 'nana', 'miss');

-- INSERT INTO public.letters (content, preview, author_id, recipient_id, likes) VALUES
-- ('Querida, queria te dizer que você é especial...', 'Querida, queria te dizer que você é especial...', 'fefe', 'nana', 1),
-- ('Meu amor, cada momento com você é precioso...', 'Meu amor, cada momento com você é precioso...', 'nana', 'fefe', 1);

-- ============================================
-- PRÓXIMOS PASSOS NO CÓDIGO
-- ============================================
-- Após executar este script, você deve:
--
-- 1. Descomentar as chamadas de API em:
--    - pages/Home.tsx: ativar letterService.getLetters()
--    - pages/Absences.tsx: ativar absenceService.getAbsences() e createAbsence
--    - pages/LetterWrite.tsx: ativar letterService.sendLetter()
--
-- 2. Configurar as variáveis de ambiente em .env.local:
--    VITE_SUPABASE_URL=seu_url_aqui
--    VITE_SUPABASE_ANON_KEY=sua_chave_aqui
--
-- 3. Verificar se lib/supabaseClient.ts está configurado corretamente
--
-- 4. Testar as funcionalidades no app
